### PR TITLE
ci(travis): add Inspec tests

### PR DESCRIPTION
**Pull request by n-rodriguez**

### CODE REVIEW

**Comment by myii** [comment]
@n-rodriguez Thanks for this.  Couple of initial points:

1. Would you mind using the very latest matrix from the `template-formula` (e.g. includes `debian-10`)?
2. Could we fix `test/salt/default/pillar/timezone.sls` to `test/salt/pillar/timezone.sls`?

**Comment by n-rodriguez** [comment]
> * Would you mind using the very latest matrix from the `template-formula` (e.g. includes `debian-10`)?
> 
> * Could we fix `test/salt/default/pillar/timezone.sls` to `test/salt/pillar/timezone.sls`?

done :)

**Comment by n-rodriguez** [comment]
I think this one is ready to be merged.

**Comment by myii** [comment]
Merged, thanks @n-rodriguez!

**Pull request merged**
